### ISSUE TITLE
Add a license for use in github linguist

### ISSUE THREAD

**Issue by cryptopapi997** [iden3/circom-highlighting-vscode#3]
This repo would be very useful for https://github.com/github/linguist/pull/6204 to add circom as a github linguist language, but needs to  have one of [these licenses](https://github.com/github/linguist/blob/9b1023ed5d308cb3363a882531dea1e272b59977/vendor/licenses/config.yml#L4-L15) to be included. It would be good to add one of these for that reason.

**Comment by cryptopapi997** [comment]
Unsure who the best person for this is, tagging @krlosMata for now as he's the latest contributor from what I can see

**Comment by krlosMata** [comment]
Hi !!
thanks for the comment. We would include a license soon

**Comment by cryptopapi997** [comment]
Awesome! Saw you added a gpl3 license, would it be possible to use any of the ones i linked above to include it in my PR for github linguist?
